# Generated by Django 5.0.2 on 2024-03-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app88', '0002_goldentries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldentries',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
